[package]
name = "imgui"
version = "0.0.6-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
description = "Experimental bindings to ocornut/imgui"
readme = "README.markdown"
homepage = "https://github.com/gekkio/imgui-rs"
repository = "https://github.com/gekkio/imgui-rs"
license = "MIT"

[features]
default = ["glium"]

[dependencies]
libc = "0.2"

[dependencies.glium]
version = "0.12"
default-features = false
optional = true

[dependencies.imgui-sys]
path = "imgui-sys"
version = "0.0.6"

[build-dependencies]
gcc = "0.3"

[dev-dependencies]
time = "0.1"

[dev-dependencies.glium]
version = "0.12"
features = ["glutin"]
default-features = false
