[package]
name = "imgui"
version = "0.0.24-pre"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "High-level Rust bindings to dear imgui"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "api-bindings"]
readme = "README.markdown"

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[dependencies]
imgui-sys = { version = "0.0.24-pre", path = "imgui-sys" }
lazy_static = "1.1"
parking_lot = "0.7"

[dev-dependencies]
memoffset = "0.3"

[workspace]
members = [
    "imgui-sys",
    "imgui-gfx-renderer",
    "imgui-glium-renderer",
    "imgui-winit-support"
]
exclude = [
    "imgui-examples",
    "imgui-glium-examples",
    "imgui-sys-bindgen"
]
