[package]
name = "imgui"
version = "0.0.23-pre"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "High-level Rust bindings to dear imgui"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "api-bindings"]
readme = "README.markdown"

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[dependencies]
glium = { version = "0.23", default-features = false, optional = true }
gfx = { version = "0.17", optional = true }
imgui-sys = { version = "0.0.23-pre", path = "imgui-sys" }

[workspace]
members = [
    "imgui-sys"
]
exclude = [
    "imgui-examples",
    "imgui-glium-examples",
    "imgui-sys-bindgen",
    "imgui-gfx-renderer",
    "imgui-glium-renderer",
    "imgui-winit-support"
]
