[package]
name = "imgui-examples"
version = "0.0.17-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "imgui crate examples"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
gfx = "0.16"
gfx_window_glutin = "0.17"
glium = { version = "0.18", default-features = true }
glutin = "0.9"
imgui = { version = "0.0.17-pre", path = "../" }
imgui-gfx-renderer = { version = "0.0.17-pre", path = "../imgui-gfx-renderer" }
imgui-glium-renderer = { version = "0.0.17-pre", path = "../imgui-glium-renderer" }
imgui-sys = { version = "0.0.17-pre", path = "../imgui-sys", features = ["gfx", "glium"] }
