[package]
name = "imgui-examples"
version = "0.0.21-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "imgui crate examples"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
gfx = "0.17"
gfx_window_glutin = "0.26"
glium = { version = "0.22", default-features = true }
glutin = "0.18"

imgui = { version = "0.0.21-pre", path = "../" }
imgui-gfx-renderer = { version = "0.0.21-pre", path = "../imgui-gfx-renderer" }
imgui-glium-renderer = { version = "0.0.21-pre", path = "../imgui-glium-renderer" }
imgui-vulkano-renderer = { version = "*", path = "../imgui-vulkano-renderer" }

image = "0.20"
winit = "0.17"
vulkano = "0.10"
vulkano-win = "0.10"
vulkano-shader-derive = "0.10"