[package]
name = "imgui-examples"
version = "0.0.23-pre"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "imgui crate examples"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
gfx = "0.17"
gfx_window_glutin = "0.28"
glutin = "0.19"
imgui = { version = "0.0.23-pre", path = "../" }
imgui-gfx-renderer = { version = "0.0.23-pre", path = "../imgui-gfx-renderer" }
imgui-winit-support = { version = "0.0.23-pre", path = "../imgui-winit-support" }
imgui-vulkano-renderer = { version = "*", path = "../imgui-vulkano-renderer" }

image = "0.21.0"
winit = "^0.17"
vulkano = "0.10"
vulkano-win = "0.10"
vulkano-shader-derive = "0.10"
