[package]
name = "imgui-examples"
version = "0.0.0"
edition = "2018"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "imgui crate examples using Glium backend"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
clipboard = "0.5"
glium = { version = "0.25", default-features = true }
image = "0.22"
imgui = { version = "0.2.0", path = "../" }
imgui-glium-renderer = { version = "0.2.0", path = "../imgui-glium-renderer" }
imgui-winit-support = { version = "0.2.0", path = "../imgui-winit-support" }
